const users = [
  {
    id: 1,
    name: "София",
    age: 22,
    gender: "female",
    distance: "1 км",
    photo: "/src/assets/images/avatars/women/woman-1.jpg",
    bio: "Люблю музыку и путешествия. Ищу интересного собеседника",
    interests: ["Фотография", "Путешествия", "Музыка"],
    isOnline: true,
  },
  {
    id: 2,
    name: "Эмили",
    age: 24,
    gender: "female",
    distance: "9 км",
    photo: "/src/assets/images/avatars/women/woman-3.jpg",
    bio: "Люблю жизнь, ищу искреннюю связь",
    interests: ["Фотография", "Путешествия", "Кошки"],
    isOnline: true,
  },
  {
    id: 3,
    name: "Мелисса",
    age: 23,
    gender: "female",
    distance: "1 км",
    photo: "/src/assets/images/avatars/women/woman-2.jpg",
    bio: "Обожаю готовить и пробовать новые рецепты",
    interests: ["Кулинария", "Йога", "Книги"],
    isOnline: false,
  },
  {
    id: 4,
    name: "Ханна",
    age: 23,
    gender: "female",
    distance: "4 км",
    photo: "/src/assets/images/avatars/women/woman-4.jpg",
    bio: "Танцую через жизнь. Давай вместе?",
    interests: ["Танцы", "Фитнес", "Кино"],
    isOnline: true,
  },
  {
    id: 5,
    name: "Юлия",
    age: 26,
    gender: "female",
    distance: "5 км",
    photo: "/src/assets/images/avatars/women/woman-5.jpg",
    bio: "Дизайнер по профессии, мечтатель по натуре",
    interests: ["Дизайн", "Искусство", "Кофе"],
    isOnline: false,
  },
  {
    id: 6,
    name: "Алекс",
    age: 25,
    gender: "male",
    distance: "3 км",
    photo: "/src/assets/images/avatars/men/man-1.jpg",
    bio: "Спорт, музыка и хорошая компания — всё что нужно",
    interests: ["Спорт", "Музыка", "Путешествия"],
    isOnline: true,
  },
  {
    id: 7,
    name: "Даниил",
    age: 27,
    gender: "male",
    distance: "6 км",
    photo: "/src/assets/images/avatars/men/man-2.jpg",
    bio: "Программист днём, гитарист ночью",
    interests: ["Программирование", "Гитара", "Игры"],
    isOnline: false,
  },
  {
    id: 8,
    name: "Максим",
    age: 24,
    gender: "male",
    distance: "2 км",
    photo: "/src/assets/images/avatars/men/man-3.jpg",
    bio: "Люблю природу и активный отдых",
    interests: ["Походы", "Фотография", "Собаки"],
    isOnline: true,
  },
  {
    id: 9,
    name: "Артём",
    age: 26,
    gender: "male",
    distance: "8 км",
    photo: "/src/assets/images/avatars/men/man-4.jpg",
    bio: "Кофеман и книголюб. Всегда готов к приключениям",
    interests: ["Книги", "Кофе", "Путешествия"],
    isOnline: false,
  },
  {
    id: 10,
    name: "Иван",
    age: 28,
    gender: "male",
    distance: "4 км",
    photo: "/src/assets/images/avatars/men/man-5.jpg",
    bio: "Шеф-повар. Накормлю вкусно и расскажу историю",
    interests: ["Кулинария", "Вино", "Кино"],
    isOnline: true,
  },
]

export default users
